modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues"

[[mods]]
    modId = "majruszsdifficulty"
    version = "${versions_mod}"
    displayName = "Majrusz's Progressive Difficulty"
    updateJSONURL = "https://raw.githubusercontent.com/Majrusz/MinecraftCommon/main/ProgressiveDifficulty/update.json"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty"
    logoFile = "logo.png"
    credits = "Thanks for all your support and downloads!"
    authors = "Majrusz"
    description = '''Mod that progressively increases the game difficulty over time.'''

[[dependencies.majruszsdifficulty]]
    modId = "forge"
    mandatory = true
    versionRange = "${versions_forge_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.majruszsdifficulty]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${versions_minecraft_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.majruszsdifficulty]]
    modId = "mlib"
    mandatory = true
    versionRange = "${versions_mlib_range}"
    ordering = "NONE"
    side = "BOTH"