modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues"

[[mods]]
    modId = "majruszsdifficulty"
    version = "1.7.4-unfinished"
    displayName = "Majrusz's Progressive Difficulty"
    updateJSONURL = "https://raw.githubusercontent.com/Majrusz/MinecraftCommon/main/ProgressiveDifficulty/update.json"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty"
    logoFile = "logo.png"
    credits = "Thanks for all your support and downloads!"
    authors = "Majrusz"
    description = '''Mod that progressively increases the game difficulty over time.'''

[[dependencies.majruszsdifficulty]]
    modId = "forge"
    mandatory = true
    versionRange = "[44.0.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.majruszsdifficulty]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.3,1.20)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.majruszsdifficulty]]
    modId = "mlib"
    mandatory = true
    versionRange = "[3.3.0,4.0.0)"
    ordering = "NONE"
    side = "BOTH"